//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public byte[] Data { get; set; }
        public string MimeType { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> User_UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
